
[ODONet]  # <tracker-name>
label = ODONet
protocol = traxpython
command = ODONet
# Specify a path to trax python wrapper if it is not visible (separate by ; if using multiple paths)
paths =  /data2/lqh/workspace_pycharm/MCITrack/external/AR_VOT20/pytracking/VOT2020
[ODONet_B384]  # <tracker-name>
label = ODONet_B384
protocol = traxpython
command = ODONet_B384
# Specify a path to trax python wrapper if it is not visible (separate by ; if using multiple paths)
paths =  /data2/lqh/workspace_pycharm/MCITrack/external/AR_VOT20/pytracking/VOT2020
[ODONet_B384_old]  # <tracker-name>
label = ODONet_B384_old
protocol = traxpython
command = ODONet_B384_old
# Specify a path to trax python wrapper if it is not visible (separate by ; if using multiple paths)
paths =  /data2/lqh/workspace_pycharm/MCITrack/external/AR_VOT20/pytracking/VOT2020